"""add_missing_column_price_per_beer_to_users

Revision ID: be62bc9da568
Revises:
Create Date: 2026-03-01 17:40:25.119690

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be62bc9da568"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "price_per_beer", sa.Integer(), nullable=False, server_default="10"
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.drop_column("price_per_beer")

    # ### end Alembic commands ###
