"""cascade delete fks

Revision ID: a7c065a371eb
Revises: be62bc9da568
Create Date: 2026-03-17 17:45:29.713542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a7c065a371eb"
down_revision: Union[str, Sequence[str], None] = "be62bc9da568"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("beer_log", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_beer_log_user_id", "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_users_group_id", "groups", ["group_id"], ["id"], ondelete="CASCADE"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "groups", ["group_id"], ["id"])

    with op.batch_alter_table("beer_log", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    # ### end Alembic commands ###
